# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('clnum', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
